apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-blue
  labels:
    app: nginx-deploy
    env: dev
spec:
  replicas: 2  # You can set the number of pods you want
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        color: blue
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80