apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: nginx-env-demo
  ports:
    - port: 80       # Port exposed by the Service
      targetPort: 80  # Port on the pod/container
  # type: ClusterIP
  type: LoadBalancer