apiVersion: apps/v1

kind: DaemonSet

metadata:

  name: fluentd

  namespace: kube-system

  labels:

    app: fluentd

spec:

  selector:

    matchLabels:

      name: fluentd

  updateStrategy:

    type: RollingUpdate

    rollingUpdate:

      maxUnavailable: 1

  template:

    metadata:

      labels:

        name: fluentd

    spec:

      tolerations:

        - key: node-role.kubernetes.io/master

          effect: NoSchedule

      containers:

        - name: fluentd

          image: fluent/fluentd-kubernetes-daemonset:v1.18-debian-elasticsearch8-1

          resources:

            limits:

              memory: 200Mi

            requests:

              cpu: 100m

              memory: 200Mi

          env:

            - name: FLUENT_ELASTICSEARCH_HOST

              value: "elasticsearch.default.svc"

            - name: FLUENT_ELASTICSEARCH_PORT

              value: "9200"

          volumeMounts:

            - name: varlog

              mountPath: /var/log

            - name: varlibdockercontainers

              mountPath: /var/lib/docker/containers

              readOnly: true

      volumes:

        - name: varlog

          hostPath:

            path: /var/log

        - name: varlibdockercontainers

          hostPath:

            path: /var/lib/docker/containers

 