apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-all-resources
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list"]
  - apiGroups: ["apps", "batch", "extensions"]
    resources: ["*"]
    verbs: ["get", "list"]
