apiVersion: v1
kind: Pod
metadata:
  name: nginx-env-demo
  labels:
    app: nginx-env-demo
spec:
  containers:
    - name: nginx
      image: kiranbangaru/docker-public:v1  
      ports:
        - containerPort: 80
      env:
        - name: WELCOME_MSG
          value: "Hello from Kubernetes NGINX!"
        - name: ENV
          value: "dev"