apiVersion: v1
kind: Pod
metadata:
  name: pod-empty-dir
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
  containers:
    - name: c1
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["echo Hello from c1 > /shared/message.txt && sleep 3600"]
      volumeMounts:
        - name: shared-data
          mountPath: /shared
    - name: c2
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["sleep 5 && cat /shared/message.txt && sleep 3600"]
      volumeMounts:
        - name: shared-data
          mountPath: /shared
