apiVersion: v1
kind: Pod
metadata:
  name: nginx-env-demo1
  labels:
    app: nginx-env-demo
spec:
  containers:
    - name: nginx
      image: kiranbangaru/docker-public:v1  
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: nginx-env-config