apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-env-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-env-demo
  template:
    metadata:
      labels:
        app: nginx-env-demo
    spec:
      containers:
        - name: nginx
          image: kiranbangaru/docker-public:v1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: nginx-env-config
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/config
              readOnly: true      
      volumes:
      - name: config-volume
        configMap:
          name: nginx-env-config
          items:
            - key: ports
              path: nginx_port.conf