apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: example1
  labels:
    app: nginx-deploy
    env: dev
spec:
  replicas: 3  # You can set the number of pods you want
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.29
          ports:
            - containerPort: 80