apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: ns01
spec:
  selector:
    app: nginx
  ports:
    -  port: 80       # Port exposed by the Service
       targetPort: 80  # Port on the pod/container
  #type: 
  type: LoadBalancer