apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pvc-deployment
  namespace: ns02
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: app
        image: nginx
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: my-storage
      volumes:
      - name: my-storage
        persistentVolumeClaim:
          claimName: pvc-example2