apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-example2
  namespace: ns02
  labels:
    type: fast
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nfs:
    path: /srv/nfs/kubedata    # Path exported by your NFS server
    server: 172.31.45.91    # Replace with your NFS server’s IP