apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-example3
  namespace: ns02
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual
  selector:
    matchLabels:
      type: fast