apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-sa-pod-reader
  namespace: dev-env
subjects:
- kind: ServiceAccount
  name: devapp-sa
  namespace: dev-env
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io