apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-user-pod-reader
  namespace: dev-env
subjects:
- kind: User
  name: user1
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io